### ISSUE TITLE
uncaught exception JsonModelFace.getColor()

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#18]
```
Render worker 6 crashed with uncaught exception.
java.lang.NullPointerException
	at se.llbit.chunky.block.ResourcepackBlockProvider$JsonModelFace.getColor(ResourcepackBlockProvider.java:613)
	at se.llbit.chunky.block.ResourcepackBlockProvider$JsonModelElement.intersect(ResourcepackBlockProvider.java:731)
	at se.llbit.chunky.block.ResourcepackBlockProvider$JsonModel.intersect(ResourcepackBlockProvider.java:805)
	at se.llbit.math.Octree.enterBlock(Octree.java:488)
	at se.llbit.chunky.renderer.scene.Scene.worldIntersection(Scene.java:638)
	at se.llbit.chunky.renderer.scene.Scene.intersect(Scene.java:614)
	at se.llbit.chunky.renderer.scene.PreviewRayTracer.nextIntersection(PreviewRayTracer.java:98)
	at se.llbit.chunky.renderer.scene.PreviewRayTracer.trace(PreviewRayTracer.java:44)
	at se.llbit.chunky.renderer.scene.Scene.rayTrace(Scene.java:594)
	at se.llbit.chunky.renderer.RenderWorker.work(RenderWorker.java:185)
	at se.llbit.chunky.renderer.RenderWorker.run(RenderWorker.java:73)

```

Unsure what block caused the issue at this time. Will look into it shortly.

[Resourcepack](https://github.com/jackjt8/TamrielCraftPack/releases/download/v1.14_b3/TCP_v1.14b3_15-16.zip)

**Comment by leMaik** [comment]
Might be fixed in more recent builds.
