### ISSUE TITLE
RuntimeException on (highly) complex model

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#19]
[Resource Pack 123MB >~ 26GB of RAM](https://mega.nz/file/6IJRQa5B#MksmOaT0kdP5PKdRqMvBKDrcpz5t5y2ojP_zVOo_i00) 

![image](https://user-images.githubusercontent.com/3740917/89815283-6fe4ae80-db3c-11ea-8e1e-81f8a250e42b.png)

```
Settings loaded from D:\Programs\Chunky_293\chunky.json
Could not find image: textures/soul_fire.png
Could not find image: textures/soul_fire.png
Loading 716 textures from C:\Users\jackj\AppData\Roaming\.minecraft\versions\1.14.4\1.14.4.jar
Found Minecraft directory C:\Users\jackj\AppData\Roaming\.minecraft
Found latest Minecraft version: C:\Users\jackj\AppData\Roaming\.minecraft\versions\1.16.1\1.16.1.jar
Loading 88 textures from C:\Users\jackj\AppData\Roaming\.minecraft\versions\1.16.1\1.16.1.jar
Failed to load textures:
	paintings_zetterstrand
Loading plugin: "chunky-denoiser-chunky2.jar"
The plugin DenoiserPlugin was developed for Chunky 2.0-beta6 but this is Chunky 1.4.5 - it may not work properly.
Plugin loaded: DenoiserPlugin 0.3.0
Building new octree (PACKED)
Building new octree (PACKED)
Building new octree (PACKED)
Building new octree (PACKED)
Settings loaded from D:\Programs\Chunky_293\chunky-launcher.json
Saved settings to D:\Programs\Chunky_293\chunky.json
Loading 716 textures from C:\Users\jackj\AppData\Roaming\.minecraft\versions\1.14.4\1.14.4.jar
Loading 88 textures from C:\Users\jackj\AppData\Roaming\.minecraft\versions\1.16.1\1.16.1.jar
Failed to load textures:
	paintings_zetterstrand
Saved settings to D:\Programs\Chunky_293\chunky.json
Loading 716 textures from C:\Users\jackj\AppData\Roaming\.minecraft\resourcepacks\TRS Textures - V.2.3.0.zip
Texture format error: ASCII font texture must be 128 by 128 pixels
Loading 176 textures from C:\Users\jackj\AppData\Roaming\.minecraft\versions\1.14.4\1.14.4.jar
Loading 78 textures from C:\Users\jackj\AppData\Roaming\.minecraft\versions\1.16.1\1.16.1.jar
Saved settings to D:\Programs\Chunky_293\chunky.json
Could not load block repeater from C:\Users\jackj\AppData\Roaming\.minecraft\resourcepacks\TRS Textures - V.2.3.0.zip/
java.lang.RuntimeException: Could not load block model truckTire from [assets, minecraft, models, truckTire.json]
	at se.llbit.chunky.block.ResourcepackBlockProvider$JsonModelLoader.getModel(ResourcepackBlockProvider.java:436)
	at se.llbit.chunky.block.ResourcepackBlockProvider$JsonModelLoader.loadBlockModel(ResourcepackBlockProvider.java:449)
	at se.llbit.chunky.block.ResourcepackBlockProvider.lambda$null$6(ResourcepackBlockProvider.java:106)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at se.llbit.chunky.block.ResourcepackBlockProvider.lambda$loadBlocks$7(ResourcepackBlockProvider.java:77)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at se.llbit.chunky.block.ResourcepackBlockProvider.loadBlocks(ResourcepackBlockProvider.java:71)
	at se.llbit.chunky.resources.TexturePackLoader.lambda$loadTexturePacks$1(TexturePackLoader.java:3670)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at se.llbit.chunky.resources.TexturePackLoader.loadTexturePacks(TexturePackLoader.java:3665)
	at se.llbit.chunky.ui.ResourceLoadOrderEditor.lambda$new$0(ResourceLoadOrderEditor.java:59)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: File not found: [Ljava.lang.String;@29d728d0
	at se.llbit.chunky.block.ResourcepackBlockProvider$MultiFileSystem.getInputStream(ResourcepackBlockProvider.java:1007)
	at se.llbit.chunky.block.ResourcepackBlockProvider$JsonModelLoader.getModel(ResourcepackBlockProvider.java:432)
	... 85 more
Could not load texture block/Tripwire
```

Credits to Luka#4234

**Comment by leMaik** [comment]
> Could not load texture block/Tripwire

@jackjt8 Does Minecraft ignore case when looking up blocks? Or does it just lookup the lowercase version (i.e. `block/tripwire`)? :thinking:

**Comment by jackjt8** [comment]
I have to assume Minecraft doesn't care about case. It seems to be able to load block/tripwire, or rather it's variants just fine.
![image](https://user-images.githubusercontent.com/3740917/90342295-f4cd3d80-dffe-11ea-9dec-b95dec26b3c5.png)

The various Tires also load correctly in Minecraft with the exception of the Truck / SUV Tire which doesn't.
![image](https://user-images.githubusercontent.com/3740917/90342330-4e356c80-dfff-11ea-92ac-3dcc655734d6.png)

**Comment by leMaik** [comment]
Hm... So instead of crashing, the truck tire block should probably just render as unknown.
