### ISSUE TITLE
Exception when trying to render

### ISSUE THREAD

**Issue by Danjb1** [leMaik/chunky#23]
### Java Version

```
>java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

### JavaFX Version

    openjfx-11.0.2_windows-x64_bin-sdk

### Launch Command

    java --module-path "C:\Program Files\Java\javafx-sdk-11.0.2\lib" --add-modules=javafx.controls,javafx.base,javafx.graphics,javafx.fxml -jar ChunkyLauncher.jar --launcher

### Launcher Options

![image](https://user-images.githubusercontent.com/26907766/104850817-35e8b700-58e9-11eb-8c56-0b0ea5dcf9f1.png)

### Steps to Reproduce

1. Open my world
2. Select some Chunks (in this case a 2x2 block)
3. Switch to "Render Preview" tab
4. Click on the play button and wait for the progress bar to complete
5. An error is logged, and nothing is rendered:

    ```
    Exception in thread "Scene Manager" java.lang.NullPointerException: Cannot invoke "se.llbit.chunky.world.WorldTexture.store(java.io.DataOutputStream)" because "waterColors" is null
	    at se.llbit.chunky.resources.OctreeFileFormat.store(OctreeFileFormat.java:129)
	    at se.llbit.chunky.renderer.scene.Scene.saveOctree(Scene.java:1884)
	    at se.llbit.chunky.renderer.scene.Scene.saveScene(Scene.java:472)
	    at se.llbit.chunky.renderer.scene.SynchronousSceneManager.saveScene(SynchronousSceneManager.java:130)
	    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$saveScene$1(AsynchronousSceneManager.java:122)
	    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:81)
    ```

**Comment by leMaik** [comment]
Finally I was able to reproduce this. :tada: 
Happens when the scene is saved without any chunks being loaded.

**Comment by leMaik** [comment]
Can't reproduce this in the latest snapshots anymore (but it was a bug in 2.3.0).
