### ISSUE TITLE
Warning: Can't save the scene right now.

### ISSUE THREAD

**Issue by commandz0** [leMaik/chunky#24]
Every time I try to save a scene, I get a warning saying "Can't save the scene right now."
There's also an error that appears in the console the first time I save a scene that says,
```
Exception in thread "Scene Manager" java.lang.NullPointerException
	at se.llbit.chunky.resources.OctreeFileFormat.store(OctreeFileFormat.java:129)
	at se.llbit.chunky.renderer.scene.Scene.saveOctree(Scene.java:1884)
	at se.llbit.chunky.renderer.scene.Scene.saveScene(Scene.java:472)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.saveScene(SynchronousSceneManager.java:130)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$saveScene$1(AsynchronousSceneManager.java:122)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:81)
```

**Comment by commandz0** [comment]
I updated to the latest snapshot and that fixed it.
